# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sulg',
            new_name='slug',
        ),
    ]
