FROM ubuntu

RUN apt-get update
RUN apt-get install -y python python-pip
RUN pip install flask

#COPY simple-web.py  /django_playlist/docker_image/flask-we-app/simple-web.py
#ENTRYPOINT FLASKAPP=/django_playlist/docker_image/flask-we-app/simple-web.py flask run --host=0.0.0.0

