---
- name: Installing and Running django Framework
  hosts: localhost

  tasks:
        - name: install django
          pip: 
              name: httpd
              state: present

        - name: started httpd
          service: 
              name: httpd
              state: started